name: SABnzbd Docker Build

on:
  schedule:
    - cron: '23 5 5 * *'
  push:
     branches: 
      - master
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: install buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v2
      with:
       buildx-version: latest
    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: build updated image
      run: |
        BDATE=$(date +%d-%m-%Y) && docker buildx build --push \
        --tag avpnusr/sabnzbd:latest --tag avpnusr/sabnzbd:$BDATE \
        --platform linux/amd64,linux/arm/v7,linux/arm64 \
        --file ./Dockerfile .
    - name: Clean
      run: |
        rm -f ${HOME}/.docker/config.json